shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
